/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package devclassmodule8;

import passenger.Passenger;
import passenger.PassengerDaoService;
import storage.ConnectionProvider;
import storage.DatabaseInitService;
import storage.StorageConstance;
import ticket.Planet;
import ticket.Ticket;
import ticket.TicketDaoService;

import java.sql.SQLException;
import java.util.concurrent.ExecutionException;

public class App {

    public static void main(String[] args) throws SQLException, ExecutionException, InterruptedException {
        new DatabaseInitService().initDb();
        ConnectionProvider connProv = new ConnectionProvider();
        PassengerDaoService psDaoServ = new PassengerDaoService(connProv.createConnection(
                StorageConstance.CONNECTION_URL
        ));
        TicketDaoService ticketDaoService = new TicketDaoService(connProv.createConnection(
                StorageConstance.CONNECTION_URL
        ));

        Passenger ps = new Passenger();
        Ticket ticket = new Ticket();

        ps.setName("Denis");
        ps.setPassport("НК100500");
        long passengerId = psDaoServ.create(ps);
        ps.setId(passengerId);

        ticket.setPassenger_id(ps.getId());
        ticket.setTo(Planet.Earth);
        ticket.setFrom(Planet.Jupiter);

        long ticketId = ticketDaoService.create(ticket);
        ticket.setId(ticketId);

        long countTicketsFromJupiter = ticketDaoService.getTicketCountToPlanet(Planet.Jupiter);
        long countTicketsFromEarth = ticketDaoService.getTicketCountToPlanet(Planet.Earth);

        System.out.println("countTicketsFromJupiter = " + countTicketsFromJupiter);
        System.out.println("countTicketsFromEarth = " + countTicketsFromEarth);


        connProv.close();
    }
}
